/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.107
 * Generated at: 2021-02-17 03:06:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.board.vo.BoardVO;
import java.util.List;

public final class listPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<BoardVO> list = (List<BoardVO>) request.getAttribute("list");
	int totalPage = (Integer) request.getAttribute("totalpage");
	int startPage = (Integer) request.getAttribute("startpage");
	int endPage = (Integer) request.getAttribute("endpage");

      out.write("\r\n");
      out.write("{\r\n");
      out.write("\t\"totalpage\" : \"");
      out.print(totalPage );
      out.write("\",\r\n");
      out.write("\t\"startpage\" : \"");
      out.print(startPage );
      out.write("\",\r\n");
      out.write("\t\"endpage\" : \"");
      out.print(endPage );
      out.write("\",\r\n");
      out.write("\t\"datas\" : [\r\n");
      out.write("\t\t");
 
			for(int i=0; i<list.size(); i++){
				BoardVO vo = list.get(i);
				if(i>0) out.print(",");
				// 이부분을 가져올때는 res.datas[i].num을 통해 가져옴
		
      out.write("\t\t\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t\"num\" : \"");
      out.print( vo.getNum() );
      out.write("\",\r\n");
      out.write("\t\t\t\t\"subject\" : \"");
      out.print( vo.getSubject() );
      out.write("\",\r\n");
      out.write("\t\t\t\t\"writer\" : \"");
      out.print( vo.getWriter() );
      out.write("\",\r\n");
      out.write("\t\t\t\t\"cont\" : \"");
      out.print( vo.getContent().replaceAll("\r", "")
				.replaceAll("\n", "<br>"));
      out.write("\",\r\n");
      out.write("\t\t\t\t\"hit\" : \"");
      out.print( vo.getHit() );
      out.write("\",\r\n");
      out.write("\t\t\t\t\"date\" : \"");
      out.print( vo.getWdate() );
      out.write("\",\r\n");
      out.write("\t\t\t\t\"mail\" : \"");
      out.print( vo.getMail() );
      out.write("\",\r\n");
      out.write("\t\t\t\t\"pass\" : \"");
      out.print( vo.getPassword() );
      out.write("\"\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t");
		
			}	
		
      out.write("\r\n");
      out.write("\t]\r\n");
      out.write("}");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
